"""Parse a Frisco inspection report PDF ("View Original Inspection PDF").

The PDF is generated by the portal (PDFKit) and has a fixed layout:

* Page 1 is an image of the Texas DSHS Food Establishment Inspection Report
  with values overlaid as text. Every value is drawn at the same position as
  a small bold field label (the labels are the template's field names), so a
  value is identified by the label it sits on. Demerit points are written
  next to the OUT box of each of the 47 numbered items.
* Pages 2+ list measured temperatures / sanitizer readings, a general
  comment, then one block per violation:

      2. Proper Cold Holding temperature(41°F/ 45°F)     <- bold
      Status: OUT
      Type: Corrected On Site / Repeat                   <- optional
      Comments: ...                                      <- may wrap
      Violation Code - *3-501.16(A)(2) - ...             <- may wrap

  Those pages repeat the page-1 header overlay in 14pt/22pt text, so only
  the 20pt body text is read.
"""

import re
import sys

import pdfplumber

LABEL_SIZE = 14
VALUE_SIZES = (22, 60)
BODY_SIZE = 20

# Page-1 header fields: (output key, label text, label x0, label top). Labels
# repeat ("Time In" is used for both time in and time out), so each field is
# pinned to where its label sits on the form. A label given as "A|B" accepts
# either text (the template has varied: "License Name" / "Establishment Name").
HEADER_FIELDS = [
    ("page_number", "pa", 1521, 152),
    ("page_count", "pa", 1583, 152),
    ("date", "Date", 74, 181),
    ("time_in", "Time In", 272, 181),
    ("time_out", "Time In", 475, 182),
    ("permit_number", "PR", 673, 179),
    ("permit_type", "PR", 1170, 179),
    ("risk_category", "Risk", 1340, 179),
    ("repeat_count", "R", 1347, 241),
    ("score", "score", 1499, 255),
    ("cos_count", "COS", 1347, 261),
    ("owner_name", "OWNERName", 605, 270),
    ("establishment_name", "License Name|Establishment Name", 66, 271),
    ("followup_required", "Followup", 1381, 302),
    ("street", "Physical address", 65, 327),
    ("city", "Physical address", 557, 327),
    ("zip", "Physical address", 826, 327),
    ("person_in_charge", "Inspector sign", 883, 1983),
    ("person_in_charge_title", "OWNERName", 1304, 2008),
    ("inspector", "Inspector sign", 882, 2036),
    ("inspector_email", "email", 1304, 2060),
]

# The item grid has two columns of OUT boxes. Points written in the left box
# (x ~ 63-80) belong to the item labelled at x ~ 778 on the same row; points
# in the middle box (x ~ 837-855) belong to the item labelled at x ~ 1622.
GRID_TOP, GRID_BOTTOM = 480, 1975
GRID_COLUMNS = [((40, 200), 778), ((800, 950), 1622)]


class ParseError(Exception):
    pass


def _size(c):
    return int(round(c["size"]))


def _is_bold(c):
    return "Bold" in c["fontname"]


def _words(page, size_pred, bold=None):
    sub = page.filter(
        lambda o: o.get("object_type") != "char"
        or (size_pred(_size(o)) and (bold is None or _is_bold(o) == bold))
    )
    return sub.extract_words(keep_blank_chars=True, x_tolerance=3, use_text_flow=True)


def parse_header(page):
    labels = _words(page, lambda s: s == LABEL_SIZE, bold=True)
    values = _words(page, lambda s: s in VALUE_SIZES, bold=False)

    slots = {}
    for key, text, x, top in HEADER_FIELDS:
        cands = [
            l for l in labels
            if l["text"].strip() in text.split("|") and abs(l["x0"] - x) < 40 and abs(l["top"] - top) < 25
        ]
        if cands:
            slots[key] = min(cands, key=lambda l: abs(l["x0"] - x) + abs(l["top"] - top))

    header = {k: None for k, *_ in HEADER_FIELDS}
    header["owner_name_truncated"] = header["establishment_name_truncated"] = False
    used = set()
    for key, label in slots.items():
        best = None
        for i, v in enumerate(values):
            dx, dy = v["x0"] - label["x0"], v["top"] - label["top"]
            # Values start at (or a few px right of) their label's x0 and
            # sit ~1px lower; the big 60pt score is offset further.
            limit_dx, limit_dy = (40, 20) if key == "score" else (40, 6)
            if -3 <= dx <= limit_dx and abs(dy) <= limit_dy and i not in used:
                if best is None or abs(dx) + abs(dy) < best[0]:
                    best = (abs(dx) + abs(dy), i)
        if best:
            used.add(best[1])
            raw = values[best[1]]["text"]
            header[key] = raw.strip()
            if key in ("owner_name", "establishment_name"):
                # The form cuts long values off; the cut leaves a trailing space.
                header[key + "_truncated"] = raw != raw.rstrip()

    unplaced = [
        v["text"] for i, v in enumerate(values)
        if i not in used and not (GRID_TOP <= v["top"] <= GRID_BOTTOM)
    ]
    header["_unplaced_values"] = unplaced
    return header, labels, values


def parse_points(labels, values):
    item_labels = []
    for l in labels:
        m = re.match(r"\s*(\d+)", l["text"])
        if m and GRID_TOP <= l["top"] <= GRID_BOTTOM:
            for _, label_x in GRID_COLUMNS:
                if abs(l["x0"] - label_x) < 15:
                    item_labels.append((label_x, l["top"], int(m.group(1))))
    points = {}
    stray = []
    for v in values:
        if not (GRID_TOP <= v["top"] <= GRID_BOTTOM):
            continue
        col = next((lx for (x0, x1), lx in GRID_COLUMNS if x0 <= v["x0"] <= x1), None)
        rows = [(abs(top - v["top"]), item) for lx, top, item in item_labels if lx == col]
        if col is None or not rows or min(rows)[0] > 20 or not v["text"].strip().isdigit():
            stray.append(v["text"])
            continue
        item = min(rows)[1]
        if item in points:
            raise ParseError(f"two point values for item {item}")
        points[item] = int(v["text"].strip())
    return points, stray


def _body_lines(pdf):
    """20pt body lines from pages 2+, each with a flag for all-bold text."""
    out = []
    for pno, page in enumerate(pdf.pages[1:], start=2):
        page = page.dedupe_chars()
        body = page.filter(
            lambda o: o.get("object_type") != "char" or _size(o) == BODY_SIZE
        )
        for line in body.extract_text_lines(return_chars=True, keep_blank_chars=True):
            text = line["text"].rstrip()
            if not text.strip():
                continue
            chars = [c for c in line["chars"] if c["text"].strip()]
            bold = bool(chars) and all(_is_bold(c) for c in chars)
            out.append({"page": pno, "text": text, "bold": bold})
    return out


# Item titles as printed on the violation pages (items not yet seen in any
# report are absent). Item headers are normally bold, but the PDF sometimes
# drops bold on the first line after a page break, so a non-bold "NN. Title"
# line also counts as a header when its title matches the known one.
KNOWN_TITLES = {
    1: 'Proper cooling time and temperature',
    2: 'Proper Cold Holding temperature(41°F/ 45°F)',
    3: 'Proper Hot Holding temperature(135°F)',
    5: 'Proper reheating procedure for hot holding (165°F in 2 Hours)',
    6: 'Time as a Public Health Control; procedures & records',
    7: 'Food and ice obtained from approved source; Food in good condition, safe, and unadulterated; parasite destruction',
    8: 'Food Received at proper temperature',
    9: 'Food Separated & protected, prevented during food preparation, storage, display, and tasting',
    10: 'Food contact surfaces and Returnables; Cleaned and Sanitized (ppm/temp)',
    11: 'Proper disposition of returned, previously served or reconditioned',
    12: 'Management, food employees and conditional employees; knowledge, responsibilities, and reporting',
    14: 'Hands cleaned and properly washed/ Gloves used properly',
    15: 'No bare hand contact with ready to eat foods or approved alternate method properly followed',
    18: 'Toxic substances properly identified, stored and used',
    19: 'Water from approved source; Plumbing installed; proper backflow device',
    20: 'Approved Sewage/Wastewater Disposal System, proper disposal',
    21: 'Person in charge present, demonstration of knowledge, and perform duties/ Certified Food Manager (CFM)',
    22: 'Food Handler/ no unauthorized persons/ personnel',
    23: 'Hot and Cold Water available; adequate pressure, safe',
    24: 'Required records available (shellstock tags; parasite destruction); Packaged Food labeled',
    25: 'Compliance with Variance, Specialized Process, and HACCP plan; Variance obtained for specialized processing methods; manufacturer instructions',
    26: 'Posting of Consumer Advisories; raw or under cooked foods (Disclosure/Reminder/Buffet Plate)/ Allergen Label',
    27: 'Proper cooling method used; Equipment Adequate to Maintain Product Temperature',
    28: 'Proper Date Marking and disposition',
    29: 'Thermometers provided, accurate, and calibrated; Chemical/ Thermal test strips',
    30: 'Food Establishment Permit (Current & Valid)',
    31: 'Adequate handwashing facilities: Accessible and properly supplied, used',
    32: 'Food and Non-food Contact surfaces cleanable, properly designed, constructed, and used',
    33: 'Warewashing Facilities; installed, maintained, used/ Service sink or curb cleaning facility provided',
    34: 'No Evidence of Insect contamination, rodent/other animals',
    35: 'Personal Cleanliness/eating, drinking or tobacco use',
    36: 'Wiping Cloths; properly used and stored',
    37: 'Environmental contamination',
    38: 'Approved thawing method',
    39: 'Utensils, equipment, & linens; properly used, stored, dried, & handled/ In use utensils; properly used',
    40: 'Single-service & single-use articles; properly stored and used',
    41: 'Original container labeling (Bulk Food)',
    42: 'Non-Food Contact surfaces clean',
    43: 'Adequate ventilation and lighting; designated areas used',
    44: 'Garbage and Refuse properly disposed; facilities maintained',
    45: 'Physical facilities installed, maintained, & clean (floors, walls, ceilings)',
    46: 'Toilet Facilities; properly constructed, supplied, and clean Adequate # of restrooms',
    47: 'Other Violations',
}


def _is_known_title(item, title):
    known = KNOWN_TITLES.get(item)
    return bool(known) and title.strip()[:30].lower() == known[:30].lower()


MEASURE_RE = re.compile(
    r"^Item:\s*(?P<item>.*?)\s+Location:\s*(?P<location>.*?)\s+"
    r"Measurement:\s*(?P<value>.*?)\s+Temperature Type:\s*(?P<unit>.*)$"
)
HEADER_RE = re.compile(r"^(\d{1,2})\.\s+(.*)$")
FIELD_RE = re.compile(r"^(Status|Type|Comments|Correct By Date):\s?(.*)$")
CODE_RE = re.compile(r"^Violation Code\s*-\s*(.*)$")


def parse_body(lines):
    raw_measurements, general, violations, warnings = [], [], [], []
    section = None  # measurements | general | violation
    cur = None
    field = None

    for ln in lines:
        text, bold = ln["text"], ln["bold"]
        if bold and text.strip() == "Measured Observations":
            # Printed at the top of every page after the first; only the
            # first occurrence starts a section.
            if section is None:
                section = "measurements"
            continue
        if text.startswith("General Comment:"):
            # Bold label; the comment (regular weight) may start on the same line.
            section, field = "general", None
            rest = text[len("General Comment:"):].strip()
            if rest:
                general.append(rest)
            continue
        m = HEADER_RE.match(text)
        if m and (bold or _is_known_title(int(m.group(1)), m.group(2))):
            cur = {
                "item_number": int(m.group(1)),
                "item_title": m.group(2).strip(),
                "status": None,
                "type": None,
                "correct_by_date": None,
                "comments": [],
                "code_lines": [],
                "page": ln["page"],
            }
            violations.append(cur)
            section, field = "violation", "title"
            continue
        if section == "violation":
            fm = FIELD_RE.match(text)
            cm = CODE_RE.match(text)
            if fm:
                field = fm.group(1).lower().replace(" ", "_")
                val = fm.group(2).strip()
                if field == "comments":
                    cur["comments"].append(val)
                else:
                    cur[field] = val
            elif cm:
                field = "code"
                cur["code_lines"].append([cm.group(1).strip()])
            elif field == "title" and bold:
                cur["item_title"] += " " + text.strip()
            elif field == "comments":
                cur["comments"].append(text.strip())
            elif field == "code":
                cur["code_lines"][-1].append(text.strip())
            else:
                raise ParseError(f"unexpected line in violation {cur['item_number']}: {text!r}")
        elif section == "measurements":
            # Each reading starts with "Item:"; a long one wraps onto the
            # following line(s), so lines are joined until the next "Item:".
            if text.strip().startswith("Item:"):
                raw_measurements.append(text.strip())
            elif raw_measurements:
                raw_measurements[-1] += " " + text.strip()
            else:
                raise ParseError(f"unexpected measurement line: {text!r}")
        elif section == "general":
            general.append(text.strip())
        else:
            raise ParseError(f"text before any section: {text!r}")

    measurements = []
    for raw in raw_measurements:
        mm = MEASURE_RE.match(raw)
        if mm:
            measurements.append({k: v.strip() for k, v in mm.groupdict().items()})
        else:
            warnings.append(f"unparsed measurement: {raw!r}")
            measurements.append({"item": raw, "location": "", "value": "", "unit": ""})

    out = []
    for v in violations:
        codes = []
        for parts in v["code_lines"]:
            full = " ".join(p for p in parts if p)
            # "<code> - <rule text>"; codes contain hyphens but never " - ".
            code, _, desc = full.partition(" - ")
            code = code.strip()
            if code in ("", "-"):
                code = ""  # printed as "Violation Code -  -": no citation entered
            codes.append({"code": code, "code_text": desc.strip()})
        vtype = (v["type"] or "").strip()
        out.append({
            "item_number": v["item_number"],
            "item_title": v["item_title"],
            "status": (v["status"] or "").strip(),
            "type": vtype,
            "corrected_on_site": "Corrected On Site" in vtype,
            "repeat": "Repeat" in vtype,
            "comments": " ".join(c for c in v["comments"] if c).strip(),
            "correct_by_date": v["correct_by_date"] or None,
            "codes": codes,
            "page": v["page"],
        })
    return measurements, " ".join(general).strip(), out, warnings


def parse_pdf(path):
    with pdfplumber.open(path) as pdf:
        first = pdf.pages[0].dedupe_chars()
        header, labels, values = parse_header(first)
        points, stray = parse_points(labels, values)
        lines = _body_lines(pdf)
        measurements, general_comment, violations, body_warnings = parse_body(lines)
        n_pages = len(pdf.pages)
    unplaced = header.pop("_unplaced_values")
    return {
        "header": header,
        "points_by_item": {str(k): v for k, v in sorted(points.items())},
        "measurements": measurements,
        "general_comment": general_comment,
        "violations": violations,
        "pdf_pages": n_pages,
        "parse_warnings": (
            [f"unplaced header value: {u!r}" for u in unplaced]
            + [f"unplaced grid value: {s!r}" for s in stray]
            + body_warnings
        ),
    }


if __name__ == "__main__":
    import json

    for p in sys.argv[1:]:
        print(json.dumps(parse_pdf(p), indent=2, ensure_ascii=False))
